### ISSUE TITLE
Writr template doesn't show up in the Configuration Manager

### ISSUE THREAD

**Issue by HMJR** [selfthinker/dokuwiki_template_writr#10]
Installed Writr and everything was ok. After switching to Monobook and back again to Writr the template doesn't show up in the Configuration Manager. This happens on all our wikis with the Writr template installed.
Tried re-install but without success.

Thanks in advance,
Henk

Dokuwiki Release 2015-08-10a "Detritus”
Writr : version ?

**Comment by selfthinker** [comment]
I cannot imagine this could have anything to do with the template. I've never come across any of this and cannot reproduce it either.
How did you install your templates? Did you do anything to your templates that was not done over the admin interface?

**Comment by HMJR** [comment]
Dear Anika,

 

First of all thanks for developing such a great template for Dokuwiki! We are now using Writr for several wiki’s and everyone is very pleased with it.

The problem we have still exists.

Today we updated one of our wikis, Extension Manager, Installed Templates, New Version 2016-03-29. No problems with updating at all.

Attached to this email are two pdf files. In first one (Configuration Settings [Offiano Foundation] 1) are the configuration settings with the Writr template. The second one the configuration settings after we switch to Bootstrap3.

As you can see on the first one there is Template? and on the second pdf all the settings of Bootstrap3 are displayed.

That’s all we have done so far. Any further help would be greatly appreciated!

Best regards,

 

Henk

 

Van: Anika Henke [mailto:notifications@github.com] 
Verzonden: vrijdag 8 april 2016 12:25
Aan: selfthinker/dokuwiki_template_writr <dokuwiki_template_writr@noreply.github.com>
CC: HMJR <webmaster@offi.info>
Onderwerp: Re: [selfthinker/dokuwiki_template_writr] Writr template doesn't show up in the Configuration Manager (#10)

 

I cannot imagine this could have anything to do with the template. I've never come across any of this and cannot reproduce it either.
How did you install your templates? Did you do anything to your templates that was not done over the admin interface?

**Comment by selfthinker** [comment]
I don't think GitHub allows attachments to email/issues. At least the PDFs are not here/attached. But I don't think it is necessary as the configuration settings will probably not tell me anything important (unless you noticed something dodgy apart from what you already described).

Can you please answer my previous questions?

> How did you install your templates? Did you do anything to your templates that was not done over the admin interface?

Specifically, did you install your various templates in different ways (upload, extension manager, git clone)?

**Comment by HMJR** [comment]
Good morning Anika,

 

In this case we started a complete new wiki with a customized download, Stable Detritus version, 4 languages and the 6 recommended popular plugins.

Through the Extension Manager Search and Install, Writr selected and installed.

After that, everything was working well, Writr template did show up in the Configuration Manager. After switching to another template, and back to Writr again Writr didn’t show up in the  Configuration Manager anymore.

To answer your questions:

 

Install as described above.

We didn’t do anything else and everything we did was done over the admin panel.

The other template was installed the same way, over the admin panel. We didn’t uploaded anything and no other modifications were made.

 

The same problem we have with other already functional wikis. 

Best regards,

 

Henk

 

Van: Anika Henke [mailto:notifications@github.com] 
Verzonden: vrijdag 8 april 2016 23:04
Aan: selfthinker/dokuwiki_template_writr <dokuwiki_template_writr@noreply.github.com>
CC: HMJR <webmaster@offi.info>
Onderwerp: Re: [selfthinker/dokuwiki_template_writr] Writr template doesn't show up in the Configuration Manager (#10)

 

I don't think GitHub allows attachments to email/issues. At least the PDFs are not here/attached. But I don't think it is necessary as the configuration settings will probably not tell me anything important (unless you noticed something dodgy apart from what you already described).

Can you please answer my previous questions?

How did you install your templates? Did you do anything to your templates that was not done over the admin interface?

Specifically, did you install your various templates in different ways (upload, extension manager, git clone)?

**Comment by selfthinker** [comment]
I have no idea what this could be. It doesn't make any sense to me.
Just to be sure, when you check the template directory (`<path_to_your_wiki>/lib/tpl/`) on your server, there is a folder called exactly "writr"?

**Comment by selfthinker** [comment]
Another thing to check might be permissions. Which file permissions does the writr directory have?

**Comment by selfthinker** [comment]
I would suggest to ask in [the forum](https://forum.dokuwiki.org/) instead. I am sure this has nothing to do with the Writr template. It will be some kind of interaction with other things (server settings or plugins or other applications, etc). And the forum will be much more capable of helping you to debug this than I am.
