### ISSUE TITLE
Footer leaks into content on some pages

### ISSUE THREAD

**Issue by kodapaio** [selfthinker/dokuwiki_template_writr#13]
Hi!

Just installed the latest version of DokuWiki and working on a migration from MediaWiki to DokuWiki at work with your template. But has run in to some small bugs...

First, on most pages: there is a bar with "start.txt · Last modified: 2016/04/28 13:30 by pontus". Is it supposed to be like that?

Please also have a look at this images:

![writr_bug1](https://cloud.githubusercontent.com/assets/9256550/14884619/5c750138-0d46-11e6-9d60-440e71e06c23.PNG)

![writr_bug2](https://cloud.githubusercontent.com/assets/9256550/14884622/6036e98a-0d46-11e6-97bf-3cfc46c9fa1f.PNG)

How to solve this?

Running the latest version of DokuWiki on Ubuntu 16.04, have tested the site in both Firefox and Thunderbird with the same result!

Best
Pontus

**Comment by selfthinker** [comment]
Fixed. Please update/re-install the template.
