### ISSUE TITLE
Problems of  visualization with large tables

### ISSUE THREAD

**Issue by EstebanMonge** [selfthinker/dokuwiki_template_writr#2]
We use to make ugly large tables, with Dokuwiki Theme in all tables comes with a usefull scrollbar... here one image with the scroll bar and the ugly table:
https://i.imgur.com/2n9n6WR.png

But with this beautiful theme we have problems the scrollbar disappears! Other image without the scrollbar but with the ugly table:
https://i.imgur.com/E2bn23f.png

How we can fix them?

Thanks!!!

**Comment by selfthinker** [comment]
This was fixed in the latest release (2015-08-24).

**Comment by EstebanMonge** [comment]
Hello I still with the same problem... I can't see scrollbar

**Comment by selfthinker** [comment]
Have you updated the template? If yes, have you done that over the extension manager or manually? If manually, have you [purged the cache](https://www.dokuwiki.org/devel:caching#purging_the_cache)?
