### ISSUE TITLE
ACL not working for topnav navigation menu

### ISSUE THREAD

**Issue by victor987** [selfthinker/dokuwiki_template_writr#3]
In a closed wiki, the *topnav* navigation menu is shown in the sidebar to non-logged users.
Even with the ACL set to None for @ALL for the [root] namespace and the *topnav* page.

**Comment by basti1dr** [comment]
:+1:

**Comment by selfthinker** [comment]
This is an issue in the core of DokuWiki, see splitbrain/dokuwiki#1369.
As soon as it is fixed in the core, this will work for this template and the topnav as well. As the issue is not reliant on this template, I will close this.
